-- one2one using primary key starts
DROP TABLE CITIZEN;
DROP TABLE ADHAAR_CARD;

CREATE TABLE CITIZEN (
   UUID varchar(32) NOT NULL ,
   NAME varchar(128) NOT NULL,
   AGE int(2) NOT NULL, 
   PRIMARY KEY (UUID)
);
CREATE TABLE ADHAAR_CARD (
   UUID varchar(32) NOT NULL,
   ADHAAR_NUMBER varchar(30) NOT NULL,
   ADHAAR_ADDRESS varchar(120) NOT NULL,
   PRIMARY KEY (UUID)
);

select * from  CITIZEN;
select * from  ADHAAR_CARD;
-- one2one using primary key ends

-- one2one using foreign key starts

DROP TABLE PERSON;
DROP TABLE PHONE_NUMBER;


CREATE TABLE PERSON(
P_UUID VARCHAR(32) NOT NULL,
NAME VARCHAR(30) NOT NULL,
AGE INT NOT NULL, 
PRIMARY KEY(P_UUID));
 
CREATE TABLE PHONE_NUMBER(
PN_UUID VARCHAR(32) NOT NULL,
PROVIDER VARCHAR(30)NOT NULL,
NUMBER VARCHAR(10) NOT NULL,
PERSON_UUID VARCHAR(32) NOT NULL,
PRIMARY KEY (PN_UUID),
KEY (PERSON_UUID),
CONSTRAINT FOREIGN KEY(PERSON_UUID) REFERENCES PERSON(P_UUID)
);

 select * from phone_number;

 select * from person;

-- one2one using foreign key ends


-- one2many foreign key starts

CREATE TABLE MERCHANT(
UUID VARCHAR(32) NOT NULL,
NAME VARCHAR(30) NOT NULL, 
OWNER VARCHAR(30) NOT NULL,
PRIMARY KEY(UUID)
);

CREATE TABLE STORE(
UUID VARCHAR(32) NOT NULL,
NAME VARCHAR(30)NOT NULL,
LOCATION VARCHAR(35) NOT NULL,
GST_NUMBER int NOT NULL,
MERCHANT_UUID VARCHAR(32) NOT NULL,
PRIMARY KEY (UUID),
KEY (MERCHANT_UUID),
CONSTRAINT FOREIGN KEY(MERCHANT_UUID) REFERENCES MERCHANT(UUID)
);
-- one2many foreign key ends


-- one2many join table starts
DROP TABLE MERCHANT2_STORE2;
DROP TABLE MERCHANT2;
DROP TABLE STORE2;


CREATE TABLE MERCHANT2(
UUID VARCHAR(32) NOT NULL,
NAME VARCHAR(120) NOT NULL, 
OWNER VARCHAR(30) NOT NULL,
PRIMARY KEY(UUID)
);


CREATE TABLE STORE2(
UUID VARCHAR(32) NOT NULL,
NAME VARCHAR(120)NOT NULL,
LOCATION VARCHAR(35) NOT NULL,
GST_NUMBER int NOT NULL, 
PRIMARY KEY (UUID) 
); 
 
CREATE TABLE MERCHANT2_STORE2(
MERCHANT2_UUID VARCHAR(32) NOT NULL,
STORE2_UUID VARCHAR(32) NOT NULL,

PRIMARY KEY(MERCHANT2_UUID,STORE2_UUID),

KEY(MERCHANT2_UUID),
KEY(STORE2_UUID),

CONSTRAINT FOREIGN KEY(STORE2_UUID) REFERENCES STORE2(UUID),
CONSTRAINT FOREIGN KEY(MERCHANT2_UUID) REFERENCES MERCHANT2(UUID)
);

select * from MERCHANT2;
select * from STORE2;
select * from MERCHANT2_STORE2;

drop table MERCHANT2_STORE2;
drop table MERCHANT2;
drop table STORE2;
-- one2many join table ends






